package com.springboot.ecommerce.entity;

import java.math.BigDecimal;

import java.util.Date;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Entity // marks the class as a JPA entity, indicating that it will be mapped to a table in the database.
@Table(name="product") //the entity is mapped to the product table in the database.
@Data
public class Product 
{
	@Id // Marks the id field as the primary key of the entity
	@GeneratedValue(strategy = GenerationType.IDENTITY) //This annotation specifies that the id field is automatically generated by the database, with an auto-incrementing strategy.
	@Column(name="id")//Maps the id field to the id column in the database.
	private Long id;
	
	@ManyToOne //This means many products can belong to one category.
	@JoinColumn(name = "category_id", nullable = false)//Specifies the foreign key column (category_id) that connects the Product entity to the ProductCategory entity. The nullable = false indicates that the product must be assigned to a category (i.e., category_id cannot be null).
	private ProductCategory category;
	
	@Column(name="sku") //Stock Keeping Unit
	private String sku;
	
	@Column(name="name")
	private String name;
	
	@Column(name="description")
	private String description;
	
	@Column(name="unit_price")
	private BigDecimal unitPrice;
	
	@Column(name="image_url")
	private String imageUrl;
	
	@Column(name="active")
	private boolean active;
	
	@Column(name="units_in_stock")
	private int unitsInStock;
	
	@Column(name="date_created")
	@CreationTimestamp //This Hibernate-specific annotation automatically sets the timestamp for the dateCreated field when a new product is created.
	private Date dateCreated;
	
	@Column(name="last_updated")
	@UpdateTimestamp //automatically updates the lastUpdated field with the current timestamp whenever the product is modified.
	private Date lastUpdated;
}
